const albumsData={

    "album":[
        {
            "title": "Absolution XX Anniversary",
            "artist":"Muse",
            "year":"2004",
            "cover": "./src/muse-absolution-xx.jpeg",
            "nCanciones": "26",
            "songs":[
                {"n":"1","title":"Intro","time":"0:22"},
                {"n":"2","title":"Apocalypse Please","time":"4:12"},
                {"n":"3","title":"Time is Running Out","time":"3:56"},
                {"n":"4","title":"Sing for Absolution","time":"4:55"},
                {"n":"5","title":"Stockholm Syndrome","time":"4:56"},
                {"n":"6","title":"Falling Away with You","time":"4:39"},
                {"n":"7","title":"Interlude","time":"0:38"},
                {"n":"8","title":"Hysteria","time":"3:47"},
                {"n":"9","title":"Blackout","time":"4:22"},
                {"n":"10","title":"Butterflies & Hurricanes","time":"5:02"},
                {"n":"11","title":"The Small Print","time":"3:28"},
                {"n":"12","title":"Fury","time":"5:00"},
                {"n":"13","title":"Endlessly","time":"3:48"},
                {"n":"14","title":"Thoughts of a Dying Atheist","time":"3:08"},
                {"n":"15","title":"Ruled by Secrecy","time":"4:52"},
                {"n":"16","title":"Apocalypse Please (Vocals and Keyboard only)","time":"4:09"},
                {"n":"17","title":"Time is Running Out (Recorded Live at The Wiltern Theater 2004)","time":"4:16"},
                {"n":"18","title":"Sing for Absolution (Recorded Live at The Antic Arena, Vienne 2004)" ,"time":"4:51"},
                {"n":"19","title":"Falling Away with You (Demo 2002)","time":"2:31"},
                {"n":"20","title":"Hysteria (Demo 2002)","time":"3:42"},
                {"n":"21","title":"Hysteria (Recorded Live at Earl's Court 2004)","time":"4:07"},
                {"n":"22","title":"Blackout (Recorded Live at The Antic Arena, Vienne 2004)","time":"4:44"},
                {"n":"23","title":"Butterflies & Hurricanes (Vocal, Keyboard and Strings Only)","time":"5:02"},
                {"n":"24","title":"Endlessly (Recorded Live at the Columbiahalle, Berlin 2003)","time":"4:02"},
                {"n":"25","title":"Thoughts of a Dying Atheist (Recorded Live at Wiltern Theater 2004)","time":"3:25"},
                {"n":"26","title":"Ruled by Secrecy (Vocals and Keyboard only)","time":"4:49"}
            ],
            "description":"Para celebrar el 20.º aniversario del álbum seminal de la banda, «Absolution», Muse ha anunciado el lanzamiento de «Muse Absolution XX Anniversary» el 17 de noviembre. Continuando con la línea de «Origin Of Muse», la edición «Muse Absolution XX Anniversary» incluye audio remasterizado, versiones en directo inéditas, demos, fotos y una entrevista a fondo con la banda, donde hablan de los altibajos del proceso de grabación, así como del entorno social en el que se encontraron y que influyó en los temas del álbum. Incluye una entrevista adicional y una sesión de preguntas y respuestas con Rich Costey. La caja de lujo se presenta en un estuche plateado e incluye un libro encuadernado en tapa dura de 40 páginas con detalles en relieve. El álbum remasterizado «Absolution» se presenta en un CD y dos vinilos plateados de 12",
            "format":"vinyl",
            "id":"0",
            "price":"2899.00"
        },
        {
            "title": "The Number of the Beast",
            "artist":"Iron Maiden",
            "year":"1982",
            "cover": "./src/ironmaiden-thenumberofthebeast.jpg",
            "nCanciones": "8",
            "songs":[
                {"n":"1","title":"Invaders","time":"3:23"},
                {"n":"2","title":"Children of the Damned","time":"4:35"},
                {"n":"3","title":"The Prisioner","time":"6:02"},
                {"n":"4","title":"22 Acacia Avenue","time":"6:36"},
                {"n":"5","title":"The Number of the Beast","time":"4:50"},
                {"n":"6","title":"Run to the Hills","time":"3:53"},
                {"n":"7","title":"Gangland","time":"3:49"},
                {"n":"8","title":"Hallowed By Thy Name","time":"7:11"},
            ],
            "description":"The Number of the Beast es el tercer álbum de estudio de la banda británica de heavy metal Iron Maiden, publicado el 22 de marzo de 1982. Este trabajo supone el primero con el vocalista Bruce Dickinson y el último con el percusionista Clive Burr. Es considerado uno de los mejores álbumes de metal de todos los tiempos.",
            "format":"cd",
            "id":"1",
            "price":"666.66"
        },
        {
            "title": "52nd Street",
            "artist":"Billy Joel",
            "year":"1978",
            "cover": "./src/billyjoel-52ndstreet.jpg",
            "nCanciones": "9",
            "songs":[
                {"n":"1","title":"Big Shot","time":"4:03"},
                {"n":"2","title":"Honesty","time":"3:53"},
                {"n":"3","title":"My Life","time":"4:44"},
                {"n":"4","title":"Zanzibar","time":"5:13"},
                {"n":"5","title":"Stiletto","time":"4:42"},
                {"n":"6","title":"Rosalinda's Eyes","time":"4:41"},
                {"n":"7","title":"Half a Mile Away","time":"4:08"},
                {"n":"8","title":"Until the Night","time":"6:35"},
                {"n":"9","title":"52nd Street","time":"2:27"},
            ],
            "description":"Después del éxito arrollador de The Stranger, Billy Joel expandió su sonido en 52nd Street, un álbum que exploró el jazz y el soft rock con una producción más refinada. Con temas como Big Shot y My Life, el disco muestra su capacidad para narrar historias urbanas con un toque de ironía y sofisticación. Ganador del Grammy a Álbum del Año, esta obra consolidó a Joel como uno de los grandes compositores de su generación.",
            "format":"cd",
            "id":"2",
            "price":"356.40"
        },
        {
            "title": "Weezer (Blue Album)",
            "artist":"Weezer",
            "year":"1994",
            "cover": "./src/weezer-weezer-bluealbum.jpg",
            "nCanciones": "10",
            "songs":[
                {"n":"1","title":"My Name Is Jonas","time":"3:24"},
                {"n":"2","title":"No One Else","time":"3:05"},
                {"n":"3","title":"The World Has Turned and Left Me Here","time":"4:20"},
                {"n":"4","title":"Buddy Holly","time":"2:39"},
                {"n":"5","title":"Undone - The Sweater Song","time":"5:06"},
                {"n":"6","title":"Surf Wax America","time":"3:06"},
                {"n":"7","title":"Say It Ain't So","time":"4:19"},
                {"n":"8","title":"In The Garage","time":"3:56"},
                {"n":"9","title":"Holiday","time":"3:25"},
                {"n":"10","title":"Only in Dreams","time":"7:09"},
            ],
            "description":"En su debut homónimo, Weezer redefinió el power pop de los 90 con una mezcla de guitarras distorsionadas y melodías pegajosas. Con la producción de Ric Ocasek (The Cars), el disco entregó himnos generacionales como Buddy Holly, Say It Ain’t So y Undone – The Sweater Song. Su combinación de sensibilidad nerd y rock alternativo lo convirtió en un clásico atemporal que marcó el inicio de la era dorada del geek rock.",
            "format":"cd",
            "id":"3",
            "price":"322.95"
        },
        {
            "title": "Pinkerton",
            "artist":"Weezer",
            "year":"1996",
            "cover": "./src/weezer-pinkerton.jpg",
            "nCanciones": "10",
            "songs":[
                {"n":"1","title":"Tired of Sex","time":"3:01"},
                {"n":"2","title":"Getchoo","time":"2:52"},
                {"n":"3","title":"No One Else","time":"3:01"},
                {"n":"4","title":"Why Bother?","time":"2:08"},
                {"n":"5","title":"Across The Sea","time":"4:32"},
                {"n":"6","title":"The Good Life","time":"4:17"},
                {"n":"7","title":"El Scorcho","time":"4:03"},
                {"n":"8","title":"Pink Triangle","time":"3:58"},
                {"n":"9","title":"Falling for You","time":"3:47"},
                {"n":"10","title":"Butterfly","time":"2:53"},
            ],
            "description":`"Pinkerton" es el segundo álbum de estudio de Weezer, lanzado en 1996. Es conocido por su tono más oscuro y emocional en comparación con el debut homónimo de la banda. El álbum explora temas de angustia, desesperación y la incomodidad de las relaciones humanas, y está inspirado en gran parte por las experiencias personales del líder de la banda, Rivers Cuomo. El sonido de "Pinkerton" es una mezcla de rock alternativo con elementos de grunge y power pop, pero con una intensidad cruda y a menudo agresiva. Canciones como "Tired of Sex" y "Across the Sea" capturan esa ansiedad y disonancia emocional, mientras que otras, como "The Good Life" y "El Scorcho", presentan letras que abordan la frustración y la alienación social. A pesar de su recepción inicial mixta, "Pinkerton" ha ganado con el tiempo un estatus de culto y se considera uno de los álbumes más influyentes de los años 90, marcando un giro en la música alternativa de la época.`,
            "format":"cd",
            "id":"4",
            "price":"355.46"
        },
        {
            "title": "Bocanada",
            "artist": "Gustavo Cerati",
            "year": "1999",
            "cover":"./src/gustavocerati-bocanada.jpg",
            "nCanciones": "15",
            "songs":[
                {"n":"1","title":"Tabú","time":"4:36"},
                {"n":"2","title":"Engaña","time":"5:01"},
                {"n":"3","title":"Bocanada","time":"5:00"},
                {"n":"4","title":"Puente","time":"5:14"},
                {"n":"5","title":"Río Babel","time":"4:41"},
                {"n":"6","title":"Beautiful","time":"6:14"},
                {"n":"7","title":"Perdonar es divino","time":"4:26"},
                {"n":"8","title":"Verbo carne","time":"5:37"},
                {"n":"9","title":"Raíz","time":"4:05"},
                {"n":"10","title":"Y si el humo está en foco...","time":"3:55"},
                {"n":"11","title":"Paseo inmoral","time":"5:31"},
                {"n":"12","title":"Aquí & ahora (Los primeros tres minutos)","time":"3:54"},
                {"n":"13","title":"Aquí & ahora (y después)","time":"2:37"},
                {"n":"14","title":"Alma","time":"4:37"},
                {"n":"15","title":"Balsa","time":"5:08"},
            ],
            "description": "Tras la disolución de Soda Stereo, Gustavo Cerati lanzó Bocanada, un álbum que rompió con las expectativas al fusionar rock, electrónica y experimentación sonora. Con una producción meticulosa, temas como Puente y Verbo Carne capturan un universo de texturas y letras introspectivas. La influencia del trip hop y la psicodelia se siente en cada rincón, convirtiéndolo en una obra maestra del rock latinoamericano.",
            "format":"cd",
            "id":"5",
            "price":"$699"
        },
        {
            "title": "Black Holes & Revelations",
            "artist": "Muse",
            "year": "2006",
            "cover":"./src/muse-blackholes&revelations.jpg",
            "nCanciones": "11",
            "songs":[
                {"n":"1","title":"Take a Bow","time":"4:35"},
                {"n":"2","title":"Starlight","time":"3:59"},
                {"n":"3","title":"Supermassive Black Hole","time":"3:29"},
                {"n":"4","title":"Map of the Problematique","time":"4:18"},
                {"n":"5","title":"Soldier's Poem","time":"2:03"},
                {"n":"6","title":"Invincible","time":"5:00"},
                {"n":"7","title":"Assassin","time":"3:31"},
                {"n":"8","title":"Exo-Politics","time":"3:53"},
                {"n":"9","title":"City of Delusion","time":"4:48"},
                {"n":"10","title":"Hoodoo","time":"3:43"},
                {"n":"11","title":"Knights of Cydonia","time":"6:06"},
            ],
            "description":"Con Black Holes & Revelations, Muse llevó su épico sonido al siguiente nivel, combinando rock progresivo, electrónica y referencias políticas. Canciones como Supermassive Black Hole y Knights of Cydonia muestran su virtuosismo y ambición sin límites. Inspirado en el caos geopolítico de la época, el álbum es una ópera moderna donde la distopía y la revolución se encuentran en cada acorde.",
            "format":"cd",
            "id":"6",
            "price":"850.56"
        },
        {
            "title":"Toxicity",
            "artist":"System of a Down",
            "year":"2001",
            "cover":"./src/systemofadown-toxicity.jpg",
            "nCanciones":"14",
            "songs":[
                {"n":"1","title":"Needles","time":"3:13"},
                {"n":"2","title":"Deer Cance","time":"2:55"},
                {"n":"3","title":"Jet Pilot","time":"2:06"},
                {"n":"4","title":"X","time":"1:58"},
                {"n":"5","title":"Chop Suey!","time":"3:30"},
                {"n":"6","title":"Bounce","time":"1:54"},
                {"n":"7","title":"Forest","time":"4:00"},
                {"n":"8","title":"ATWA","time":"2:56"},
                {"n":"9","title":"Science","time":"2:43"},
                {"n":"10","title":"Shimmy","time":"1:51"},
                {"n":"11","title":"Toxicity","time":"3:39"},
                {"n":"12","title":"Prison Song","time":"3:31"},
                {"n":"13","title":"Psycho","time":"3:45"},
                {"n":"14","title":"Aerials","time":"6:11"},
            ],
            "description":"Un huracán de energía y protesta, Toxicity elevó a System of a Down a la cima del nu-metal con una mezcla única de thrash, melodías armenias y letras incendiarias. Con himnos como Chop Suey! y Aerials, el álbum equilibra agresión y belleza, abordando temas como la política, la guerra y la adicción con una intensidad que pocos han logrado replicar.",
            "format":"cd",
            "id":"7",
            "price":"459.99"
            },
            {
                "title":"Ride the Lightning",
                "artist":"Metallica",
                "year":"1984",
                "cover":"./src/metallica-ridethelightning.jpeg",
                "nCanciones":"8",
                "songs":[
                {"n":"1","title":"Fight Fire with Fire","time":"4:44"},
                {"n":"2","title":"Ride the Lightning","time":"6:36"},
                {"n":"3","title":"For Whom the Bell Tolls","time":"5:10"},
                {"n":"4","title":"Fade to Black","time":"6:57"},
                {"n":"5","title":"Trapped Under Ice","time":"4:03"},
                {"n":"6","title":"Escape","time":"4:23"},
                {"n":"7","title":"Creeping Death","time":"6:36"},
                {"n":"8","title":"The call of Ktulu","time":"8:53"},
            ],
            "description":"Más ambicioso y sofisticado que su predecesor, Ride the Lightning redefinió el thrash metal con composiciones épicas y mayor madurez lírica. Desde la brutalidad de Fight Fire with Fire hasta la majestuosidad de Fade to Black, el álbum demuestra el crecimiento de Metallica como compositores, estableciendo un estándar que influenciaría a generaciones enteras del metal.",
            "format":"cd",
            "id":"8",
            "price":"379.99"
            },
            {
                "title":"HIT ME HARD AND SOFT",
                "artist":"Billie Eilish",
                "year":"2024",
                "cover":"./src/billieeilish-hitmehardandsoft.jpg",
                "nCanciones":"10",
                "songs":[
                    {"n":"1","title":"Skinny","time":"3:39"},
                    {"n":"2","title":"Lunch","time":"2:59"},
                    {"n":"3","title":"Chihiro","time":"5:03"},
                    {"n":"4","title":"Birds of a Feather","time":"3:30"},
                    {"n":"5","title":"Wildflower","time":"4:21"},
                    {"n":"6","title":"The Greatest","time":"4:53"},
                    {"n":"7","title":"L'amour de ma vie","time":"5:33"},
                    {"n":"8","title":"The Diner","time":"3:06"},
                    {"n":"9","title":"Bittersuite","time":"4:58"},
                    {"n":"10","title":"Blue","time":"5:43"},
                ],
                "description":"En su álbum más introspectivo y experimental hasta la fecha, Billie Eilish fusiona minimalismo, pop alternativo y producción cinematográfica. Hit Me Hard and Soft es un viaje sonoro donde la vulnerabilidad y la oscuridad conviven en perfecta armonía. Canciones como Lunch y The Greatest demuestran su evolución artística, mientras que la producción de Finneas mantiene la esencia etérea y melancólica que la define.",
                "format":"cd",
                "id":"9",
                "price":"500.78"
            },
            {
                "title":"Demon Days",
                "artist":"Gorillaz",
                "year":"2005",
                "cover":"./src/gorillaz-demondays.jpg",
                "nCanciones":"15",
                "songs":[
                    {"n":"1","title":"Intro","time":"1:03"},
                    {"n":"2","title":"Last Living Souls","time":"3:10"},
                    {"n":"3","title":"Kids with Guns","time":"3:45"},
                    {"n":"4","title":"O Green Word","time":"4:31"},
                    {"n":"5","title":"Dirty Harry","time":"3:43"},
                    {"n":"6","title":"Feel Good Inc.","time":"3:41"},
                    {"n":"7","title":"El Mañana","time":"3:50"},
                    {"n":"8","title":"Every Planet We Reach is Dead","time":"4:53"},
                    {"n":"9","title":"November Has Come","time":"2:41"},
                    {"n":"10","title":"All Alone","time":"3:30"},
                    {"n":"11","title":"White Light","time":"2:08"},
                    {"n":"12","title":"DARE","time":"4:04"},
                    {"n":"13","title":"Fire Coming Out of the Monkey's Head","time":"3:16"},
                    {"n":"14","title":"Don't Get Lost in Heaven","time":"2:00"},
                    {"n":"15","title":"Demon Days","time":"4:28"},
                ],
                "description":"Una odisea sonora post-apocalíptica, Demon Days es el álbum que consagró a Gorillaz como una de las propuestas más innovadoras del nuevo milenio. Con la producción de Danger Mouse, el disco combina hip-hop, rock y electrónica en temas como Feel Good Inc. y DARE. Más que un álbum, es una distopía musical donde la desesperanza y la esperanza bailan en un mismo loop.",
                "format":"cd",
                "id":"10",
                "price":"$438.65"
            },
            {
                "title":"Ten Thousand Fists",
                "artist":"Disturbed",
                "year":"2005",
                "cover":"./src/disturbed-tenthousandfists.jpg",
                "nCanciones":"14",
                "songs":[
                    {"n":"1","title":"Ten Thousand Fists","time":"3:33"},
                    {"n":"2","title":"Just Stop","time":"3:46"},
                    {"n":"3","title":"Guarded","time":"3:22"},
                    {"n":"4","title":"Deify","time":"4:18"},
                    {"n":"5","title":"Stricken","time":"4:07"},
                    {"n":"6","title":"I'm Alive","time":"4:42"},
                    {"n":"7","title":"Sons of Plunder","time":"3:51"},
                    {"n":"8","title":"Overburdened","time":"5:59"},
                    {"n":"9","title":"Decadence","time":"3:27"},
                    {"n":"10","title":"Forgiven","time":"4:15"},
                    {"n":"11","title":"Land of Confusion","time":"4:50"},
                    {"n":"12","title":"Sacred Lie","time":"3:08"},
                    {"n":"13","title":"Pain Redefined","time":"4:10"},
                    {"n":"14","title":"Avarice","time":"2:57"},
                ],
                "description":"Ten Thousand Fists es el tercer álbum de la banda de hard rock Disturbed, lanzado en 2005. Es un álbum que fusiona la oscuridad y brutalidad de The Sickness (2000) con la complejidad y melodía de Believe (2002).",
                "format":"cd",
                "id":"11",
                "price":"430:50"
            },
            {
                "title":"The Eminem Show(Expanded Edition)",
                "artist":"Eminem",
                "year":"2022",
                "cover":"./src/eminem-theeminemshow-expandededition.jpg",
                "nCanciones":"38",
                "songs":[
                    {"n":"1","title":"Curtains Up - Skit","time":"0:29"},
                    {"n":"2","title":"White America","time":"5:24"},
                    {"n":"3","title":"Business","time":"4:11"},
                    {"n":"4","title":"Cleanin' Out My Closet","time":"4:57"},
                    {"n":"5","title":"Square Dance","time":"5:23"},
                    {"n":"6","title":"The Kiss - Skit","time":"1:15"},
                    {"n":"7","title":"Soldier","time":"3:46"},
                    {"n":"8","title":"Say Goodbye Hollywood","time":"4:32"},
                    {"n":"9","title":"Drips","time":"4:45"},
                    {"n":"10","title":"Without me","time":"4:50"},
                    {"n":"11","title":"Paul Rosenberg - Skit","time":"0:22"},
                    {"n":"12","title":"Sing For The Moment","time":"4:50"},
                    {"n":"13","title":"Superman","time":"5:50"},
                    {"n":"14","title":"Hailie's Song","time":"5:20"},
                    {"n":"15","title":"Steve Berman - Skit","time":"0:33"},
                    {"n":"16","title":"When the music Stops","time":"4:29"},
                    {"n":"17","title":"Say What You Say","time":"5:09"},
                    {"n":"18","title":"Till I Collapse","time":"4:57"},
                    {"n":"19","title":"My Dad's Gone Crazy","time":"4:27"},
                    {"n":"20","title":"Curtains Close","time":"1:01"},
                    {"n":"21","title":"Stimulate","time":"5:03"},
                    {"n":"22","title":"The Constpiracy Freestyle","time":"2:50"},
                    {"n":"23","title":"Bump Heads","time":"4:41"},
                    {"n":"24","title":"Jimmy, Brian and Mike","time":"3:21"},
                    {"n":"25","title":"Freestyle #1 - Live From Tramps, New York/1999","time":"1:17"},
                    {"n":"26","title":"Brain Damage - Live From Tramps, New York/1999","time":"1:24"},
                    {"n":"27","title":"Freestyle #2 - Live From Tramps, New York/1999","time":"0:52"},
                    {"n":"28","title":"Just Don't Give a Fuck - Live From Tramps, New York/1999","time":"3:15"},
                    {"n":"29","title":"The Way I am - Live From Fuji Rock Festival, Japan/2001","time":""},
                    {"n":"30","title":"The Real Slam Shady - Live From Fuji Rock Festival, Japan/2001","time":"4:45"},
                    {"n":"31","title":"Business - Instrumental","time":"4:11"},
                    {"n":"32","title":"Cleanin' Out My Closet - Instrumental","time":"4:11"},
                    {"n":"33","title":"Square Dance - Instrumental","time":"5:42"},
                    {"n":"34","title":"Without Me - Instrumental","time":"4:48"},
                    {"n":"35","title":"Sing For The Moment - Instrumental","time":"6:23"},
                    {"n":"36","title":"Superman - Instrumental","time":"7:02"},
                    {"n":"37","title":"Say What You Say -Instrumental","time":"5:06"},
                    {"n":"38","title":"Till I Collapse - Instrumental","time":"5:45"},
                ],
                "description":"The Eminem Show es el cuarto álbum de estudio del rapero estadounidense Eminem, el tercero tras firmar por Aftermath, lanzado en 2002. Fue el álbum musical más vendido ese año en todo el mundo con 22 millones de copias.",
                "format":"cd",
                "id":"12",
                "price":"1949.00"
            },
            {
                "title":"Vida de Perros",
                "artist":"Los Bunkers",
                "year":"2005",
                "cover":"./src/losbunkers-vidadeperros.jpg",
                "nCanciones":"11",
                "songs":[
                    {"n":"1","title":"Ven Aquí","time":"3:38"},
                    {"n":"2","title":"Nada más de mí","time":"3:14"},
                    {"n":"3","title":"Llueve Sobre la Ciudad","time":"3:57"},
                    {"n":"4","title":"Tú","time":"3:06"},
                    {"n":"5","title":"Maribel","time":"4:08"},
                    {"n":"6","title":"Ahora Que No Estás","time":"5:52"},
                    {"n":"7","title":"Miéntele","time":"3:59"},
                    {"n":"8","title":"Nada es Igual","time":"3:57"},
                    {"n":"9","title":"Te Vistes Y Te Vas","time":"3:30"},
                    {"n":"10","title":"Vida de Perros","time":"3:36"},
                    {"n":"11","title":"Hoy","time":"3:43"},
                ],
                "description":"Vida de perros es el cuarto álbum de la banda chilena Los Bunkers, lanzado el 8 de septiembre de 2005. Es considerado uno de los discos más exitosos que el grupo chileno ha publicado, siendo editado paralelamente en Estados Unidos y México, que permitirá la internacionalización de la banda.",
                "format":"cd",
                "id":"13",
                "price":"1490.01"
            },
            {
                "title":"The Golden Age of Gotesque",
                "artist":"Marilyn Manson",
                "year":"2003",
                "cover":"./src/marilynmanson-thegoldenageofgrotesque.jpg",
                "nCanciones":"18",
                "songs":[
                    {"n":"1","title":"Thaeter","time":"1:14"},
                    {"n":"2","title":"This Is the New *hit","time":"4:20"},
                    {"n":"3","title":"mOBSCENE","time":"3:27"},
                    {"n":"4","title":"Doll-Dagga Buzz-Buzz Ziggety","time":"4:11"},
                    {"n":"5","title":"Use your fist and Not Your Mouth","time":"3:35"},
                    {"n":"6","title":"The Golden Age of Grotesque","time":"4:05"},
                    {"n":"7","title":"(s)AINT","time":"3:35"},
                    {"n":"8","title":"Ka-Boom Ka-Boom","time":"4:03"},
                    {"n":"9","title":"Slutgarden","time":"4:07"},
                    {"n":"10","title":"♠","time":"4:35"},
                    {"n":"11","title":"Para-Noir","time":"6:01"},
                    {"n":"12","title":"The Bright Young Things","time":"4:19"},
                    {"n":"13","title":"Better of Tow Evils","time":"3:48"},
                    {"n":"14","title":"Vodevil","time":"4:40"},
                    {"n":"15","title":"Obsequey (The death of art)","time":"1:48"},
                    {"n":"16","title":"Tainted Love","time":"3:20"},
                    {"n":"17","title":"Baboon Rape Party","time":"2:42"},
                    {"n":"18","title":"Paranoiac","time":"3:58"},
                ],
                "description":"En este disco Manson cambia de estilo. Según sus declaraciones, consideró que ya había dicho todo lo que tenía que decir sobre la religión, la sociedad, etc. y por ello esta vez procuró hacer un disco menos serio, alegre, centrado en el erotismo y en lo irracional.",
                "format":"cd",
                "id":"14",
                "price":"435.00"
            },
            {
                "title":"Master Of Puppets (Remastered)",
                "artist":"Matallica",
                "year":"1986",
                "cover":"./src/metallica-masterofpuppets.jpg",
                "nCanciones":"8",
                "songs":[
                    {"n":"1","title":"Battery","time":"5:12"},
                    {"n":"2","title":"Master Of Puppets","time":"8:35"},
                    {"n":"3","title":"The Thing That Should Not Be","time":"6:32"},
                    {"n":"4","title":"Welcome Home /Sanitarium)","time":"6:28"},
                    {"n":"5","title":"Disposable Heroes","time":"8:14"},
                    {"n":"6","title":"Leper Messiah","time":"5:38"},
                    {"n":"7","title":"Orion","time":"8:12"},
                    {"n":"8","title":"Damage, Inc.","time":"5:08"},
                ],
                "description":"Master Of Puppets es el tercer álbum de estudio del grupo musical de thrash metal.  El álbum fue el primer disco de oro de la banda tras vender 500 000 copias en Estados Unidos, aunque luego superaría las 6 millones.",
                "format":"cd",
                "id":"15",
                "price":"939.00"
            },
            {
                "title":"Bad (Remastered)",
                "artist":"Michael Jackson",
                "year":"2987",
                "cover":"./src/michaeljackson-bad.jpg",
                "nCanciones":"11",
                "songs":[
                    {"n":"1","title":"Bad","time":"4:07"},
                    {"n":"2","title":"The Way You Make Me Feel","time":"4:58"},
                    {"n":"3","title":"Speed Demon","time":"4:03"},
                    {"n":"4","title":"Liberian Girl","time":"3:52"},
                    {"n":"5","title":"Just Good Friends","time":"4:07"},
                    {"n":"6","title":"Another Part of Me","time":"3:55"},
                    {"n":"7","title":"Man in the Mirror","time":"5:17"},
                    {"n":"8","title":"I Just Can't Stop Loving You ","time":"4:12"},
                    {"n":"9","title":"Dirty Diana","time":"4:41"},
                    {"n":"10","title":"Smooth Criminal","time":"4:18"},
                    {"n":"11","title":"Leave Me Alone","time":"4:40"},
            
                ],
                "description":"Bad es el séptimo álbum de estudio del cantante estadounidense Michael Jackson, publicado el 31 de agosto de 1987 por Epic Records. El álbum fue escrito y grabado en un periodo de casi un año y marcó la colaboración final entre el intérprete y el productor Quincy Jones.",
                "format":"cd",
                "id":"16",
                "price":"407.90"
            },
            {
                "title":"Drones",
                "artist":"Muse",
                "year":"2015",
                "cover":"./src/muse-drones.jpg",
                "nCanciones":"12",
                "songs":[
                    {"n":"1","title":"Dead Inside","time":"4:23"},
                    {"n":"2","title":"[Drill Sergeant]","time":"0:21"},
                    {"n":"3","title":"Psycho","time":"5:17"},
                    {"n":"4","title":"Mercy","time":"3:52"},
                    {"n":"5","title":"Reapers","time":"6:00"},
                    {"n":"6","title":"The Handler","time":"4:34"},
                    {"n":"7","title":"[FJK]","time":"0:55"},
                    {"n":"8","title":"Defector","time":"4:33"},
                    {"n":"9","title":"Revolt","time":"4:06"},
                    {"n":"10","title":"Aftermeth","time":"5:48"},
                    {"n":"11","title":"The Globalist","time":"10:07"},
                    {"n":"12","title":"Drones","time":"2:52"},
                ],
                "description":"Drones es el séptimo álbum de estudio de la banda de rock alternativo británica Muse, lanzado el 5 de junio de 2015 a través de Warner Bros. Records y Helium 3. Tras el álbum The 2nd Law en el que Muse se había alejado de su sonido característico, “Drones” es un retorno a sus raíces de rock progresivo y alternativo.",
                "format":"cd",
                "id":"17",
                "price":"880.00"
            },
            {
                "title":"Origin of Symmetry",
                "artist":"Muse",
                "year":"2001",
                "cover":"./src/muse-originofsymmetry.jpeg",
                "nCanciones":"11",
                "songs":[
                    {"n":"1","title":"New Born","time":"6:03"},
                    {"n":"2","title":"Bliss","time":"4:12"},
                    {"n":"3","title":"Space Dementia","time":"6:21"},
                    {"n":"4","title":"Hyper Music","time":"3:21"},
                    {"n":"5","title":"Plug In Baby","time":"3:40"},
                    {"n":"6","title":"Citizen Erased","time":"7:19"},
                    {"n":"7","title":"Microcuts","time":"3:39"},
                    {"n":"8","title":"Screenager","time":"4:20"},
                    {"n":"9","title":"Darkshines","time":"4:47"},
                    {"n":"10","title":"Feeling Good","time":"3:19"},
                    {"n":"11","title":"Megalomania","time":"4:38"},
                ],
                "description":"Origin of Symmetry is the second studio album by English rock band Muse, released on 18 June 2001 through Taste Media.",
                "format":"cd",
                "id":"18",
                "price":"449.00"
            },
            {
                "title":"Origin of Symmetry (XX Anniversary RemiXX)",
                "artist":"Muse",
                "year":"2021",
                "cover":"./src/muse-originofsymmetry-xxanniversaryremixx.jpg",
                "nCanciones":"12",
                "songs":[
                    {"n":"1","title":"New Born - XX Anniversary RemiXX","time":"6:03"},
                    {"n":"2","title":"Bliss - XX Anniversary RemiXX","time":"4:14"},
                    {"n":"3","title":"Space Dementia - XX Anniversary RemiXX","time":"6:21"},
                    {"n":"4","title":"Hyper Music - XX Anniversary RemiXX","time":"3:21"},
                    {"n":"5","title":"Plug In Baby - XX Anniversary RemiXX","time":"3:39"},
                    {"n":"6","title":"Citizen Erased (XX Anniversary RemiXX)","time":"7:18"},
                    {"n":"7","title":"Micro Cuts - XX Anniversary RemiXX","time":"3:38"},
                    {"n":"8","title":"Screenager - XX Anniversary RemiXX","time":"4:20"},
                    {"n":"9","title":"Darkshines - XX Anniversary RemiXX","time":"4:46"},
                    {"n":"10","title":"Feeling Good - XX Anniversary RemiXX","time":"3:18"},
                    {"n":"11","title":"Futurism - XX Anniversary RemiXX","time":"3:27"},
                    {"n":"12","title":"Megalomania - XX Anniversary RemiXX","time":"4:38"},
                ],
                "description":"Muse celebra el 20 aniversario de su álbum “Origin of symmetry” con el lanzamiento de una nueva edición remasterizada y remezclada.",
                "format":"cd",
                "id":"19",
                "price":"629.80"
            },
            {
                "title":"Showbiz",
                "artist":"Muse",
                "year":"1999",
                "cover":"./src/muse-showbiz.jpg",
                "nCanciones":"13",
                "songs":[
                    {"n":"1","title":"Sunburn","time":"3:54"},
                    {"n":"2","title":"Muscle Museum","time":"4:23"},
                    {"n":"3","title":"Filip","time":"4:02"},
                    {"n":"4","title":"Falling Down","time":"4:34"},
                    {"n":"5","title":"Cave","time":"4:47"},
                    {"n":"6","title":"Showbiz","time":"5:17"},
                    {"n":"7","title":"Unintended","time":"3:58"},
                    {"n":"8","title":"Uno","time":"3:39"},
                    {"n":"9","title":"Sober","time":"4:05"},
                    {"n":"10","title":"Escape","time":"3:32"},
                    {"n":"11","title":"Overdue","time":"2:27"},
                    {"n":"12","title":"Hate This and I'll Love You","time":"5:10"},
                    {"n":"13","title":"Spiral Static","time":"4:44"},
                ],
                "description":"Showbiz es el primer álbum de estudio de la banda inglesa de rock, Muse. Fue lanzado en el Reino Unido bajo la productora Taste Media el 7 de septiembre de 1999 en Francia, el 28 de septiembre en los Estados Unidos y el 4 de octubre en el resto del mundo.",
                "format":"cd",
                "id":"20",
                "price":"882.42"
            },
            {
                "title":"Simulation Theory",
                "artist":"Muse",
                "year":"2018",
                "cover":"./src/muse-simulationtheory.jpg",
                "nCanciones":"11",
                "songs":[
                    {"n":"1","title":"Algorithm","time":"4:05"},
                    {"n":"2","title":"The Dark Side","time":"3:47"},
                    {"n":"3","title":"Pressure","time":"3:55"},
                    {"n":"4","title":"Propaganda","time":"3:00"},
                    {"n":"5","title":"Break It To Me","time":"3:37"},
                    {"n":"6","title":"Something Human","time":"3:46"},
                    {"n":"7","title":"Thought Contagion","time":"3:26"},
                    {"n":"8","title":"Get Up and Fight","time":"4:04"},
                    {"n":"9","title":"Blockades","time":"3:50"},
                    {"n":"10","title":"Dig Down","time":"3:48"},
                    {"n":"11","title":"The Void","time":"4:44"},
                ],
                "description":"«Simulation Theory» incorpora influencias de la ciencia ficción, los videojuegos, la realidad virtual, y la cultura pop de los años 80. Explora la hipótesis del filósofo Nick Bostrom que teoriza que la humanidad podría estar viviendo en una realidad simulada",
                "format":"cd",
                "id":"21",
                "price":"707.00"
            },
            {
                "title":"The 2nd Law",
                "artist":"Muse",
                "year":"2012",
                "cover":"./src/muse-the2ndlaw.jpg",
                "nCanciones":"13",
                "songs":[
                    {"n":"1","title":"Supremacy","time":"4:56"},
                    {"n":"2","title":"Madness","time":"4:38"},
                    {"n":"3","title":"Panic Station [Explicit]","time":"3:05"},
                    {"n":"4","title":"Prelude","time":"0:58"},
                    {"n":"5","title":"Survival","time":"4:18"},
                    {"n":"6","title":"Follow Me","time":"3:51"},
                    {"n":"7","title":"Animals","time":"4:23"},
                    {"n":"8","title":"Explorers","time":"5:47"},
                    {"n":"9","title":"Big Freeze","time":"4:40"},
                    {"n":"10","title":"Save Me","time":"5:09"},
                    {"n":"11","title":"Liquid State","time":"3:03"},
                    {"n":"12","title":"The 2nd Law: Unsustainable","time":"3:49"},
                    {"n":"13","title":"The 2nd Law: Isolated System","time":"5:00"},
                ],
                "description":"El álbum, que toma su nombre de la Segunda Ley de la Termodinámica, es un trabajo conceptual sobre un planeta en deterioro en el que la vida se ha vuelto insostenible.",
                "format":"cd",
                "id":"22",
                "price":"399.00"
            },
            {
                "title":"The Resistance",
                "artist":"Muse",
                "year":"",
                "cover":"./src/muse-theresistance.jpg",
                "nCanciones":"",
                "songs":[
                    {"n":"","title":"","time":""},
                ],
                "description":"",
                "format":"cd",
                "id":"",
                "price":""
            },
            {
                "title":"",
                "artist":"",
                "year":"",
                "cover":"",
                "nCanciones":"",
                "songs":[
                    {"n":"","title":"","time":""},
                ],
                "description":"",
                "format":"cd",
                "id":"",
                "price":""
            }
        ]
    }
    